### ISSUE TITLE
Unbreak sbt.ScriptMain

### ISSUE THREAD

**Issue by dwijnand** [paulp/sbt-extras#122]
The changes around JAVA_HOME and setting javaHome in #95 broke sbt.ScriptMain.

See https://github.com/paulp/sbt-extras/pull/95#discussion_r29108334

**Comment by dwijnand** [comment]
I propose removing all the logic around setting `javaHome` as I've found http://www.jenv.be/ to be a better solution.

Among other things this would solve #99.

**Comment by dwijnand** [comment]
Here's an example scala script (using sbt.ScriptMain), after #142:

```scala
#!/usr/bin/env sbt -script

/***
scalaVersion := "2.11.8"
*/

println(scala.util.Properties.versionNumberString)
```

**Comment by dwijnand** [comment]
The above script doesn't work with current master, provided you have a JAVA_HOME set so it can break this:

```bash
$ export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
$ ./shout.scala
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/0.13/plugins
java.io.FileNotFoundException: /s/warn (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
```

**Comment by paulp** [comment]
As a rule, shebang lines like
```bash
#!/usr/bin/env sbt -script
```
don't work. It makes the whole endeavor a giant pain. See [some discussion at stackoverflow](http://stackoverflow.com/questions/4303128/how-to-use-multiple-arguments-with-a-shebang-i-e). You cannot rely on being able to pass more than one argument to env.

**Comment by dwijnand** [comment]
Oh wonderful..
