### ISSUE TITLE
Setup Travis to test on OS X

### ISSUE THREAD

**Issue by dwijnand** [paulp/sbt-extras#126]
I recently found out, via @Nava2 on #125 (which is also relevant to this ticket), that Travis supports OS X:

https://docs.travis-ci.com/user/osx-ci-environment/

Given that sbt-extras intends to support both Linux and OS X we should setup it up to test both.

**Comment by Nava2** [comment]
I'll take this on, I'm already working on it.

**Comment by dwijnand** [comment]
I see. Go for it it would be a great addition.
