### ISSUE TITLE
Consider adding a version, perhaps timestamp

### ISSUE THREAD

**Issue by dwijnand** [paulp/sbt-extras#137]
It would be very useful if it were possible to easily identify the version of the sbt script, for instance when outputting the usage text.

I was thinking perhaps a timestamp would do, enforced by a test that runs (1) only on Travis, and (2) only when testing a pull request (so that it doesn't break git bisect).

**Comment by dwijnand** [comment]
The timestamp to use is the git commit timestamp, not the current timestamp.

That avoids problems of when the check is performed. And I think git bisect would be fine too.

I'm such a monkey for not thinking about that, and thinking to use the _current_ timestamp.. -.-

**Comment by paulp** [comment]
One problem with this is that with no layer between the bash source and the deployed script, the repository history would be noisified by an endless series of meaningless changes. And if the script is to be self-contained, then it has to somehow have the timestamp updated on every commit, and there's no mechanism for enforcing that it happens. Much like the problem of automatically formatting code. I can't get behind anything which involves a new human-performed step on every commit.

**Comment by dwijnand** [comment]
Oh yeah, forgot about that part..

If you don't mind the extra per-PR commit, this could be dealt with by Travis CI. I believe I had evidence that it can push commits back. Probably with `[ci skip]` in the commit message.

**Comment by paulp** [comment]
I think the relative simplicity around here is a big asset and I am loathe to give any of it up. I don't think this purpose warrants it.

**Comment by dwijnand** [comment]
I understand that.

Do you have any alternative solutions without these kinds of drawbacks?

**Comment by paulp** [comment]
Only ones which move away from being a self-contained download-and-immediately-run script.

**Comment by dwijnand** [comment]
Personally I'd rather the extra commits than not being able to symlink right out of the repo or curl it out down from GitHub.

Closing this, at least for now.
