### ISSUE TITLE
Environment variables in .sbtopts file are not replaced

### ISSUE THREAD

**Issue by fernandoacorreia** [paulp/sbt-extras#145]
In a project which has a `.sbtopts` in the project root with a contents like this:

```
-Dmongodb.default.uri=mongodb://${DOCKER_HOST_IP}:27017/database
```

the Java property at runtime contains the literal `${DOCKER_HOST_IP}` string on it instead of the value of the environment variable.

When running `sbt` [installed from a deb package](http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Linux.html#Ubuntu+and+other+Debian-based+distributions), the environment variables are replaced.

**Comment by paulp** [comment]
There's no such feature here. Presumably they added that in the "official" runner. Even if I wanted to add it, it would be a breaking change, which is not likely at this point.
