### ISSUE TITLE
Question: IntelliJ and sbt-extras

### ISSUE THREAD

**Issue by rbellamy** [paulp/sbt-extras#163]
Recent versions of the IntelliJ IDEA Scala plugin have a test to see if the Custom SBT is actually a JAR, which means I can no longer just point to `/usr/bin/sbt` like I used to...

Which means that for IntelliJ, I have two choices:
1. Use the bundled version of SBT (used to be terrible, is still not awesome).
2. Uninstall this (awesome) script, and use `sbt` from Community.

I don't like either of those choices - any recommendations for using `sbt-extras` with IntelliJ?

**Comment by dwijnand** [comment]
Why do you need to uninstall this script?

**Comment by rbellamy** [comment]
I guess I wasn't very clear.

When I try to use an external `sbt` with IntelliJ, I used to be able to point IntelliJ directly to `/usr/bin/sbt`.
![selection 632x900 20160902103120](https://cloud.githubusercontent.com/assets/94763/18212507/797ece74-70f8-11e6-965e-3fcf230161fb.png)

That no longer works because IntelliJ is looking for a "real" JAR.

I suppose I could point at `~/.sbt/launchers/0.13.11/sbt-launcher.jar`

**Comment by dwijnand** [comment]
Yep, that's what I would suggest.
