### ISSUE TITLE
-Dconfig.file ignored

### ISSUE THREAD

**Issue by rbellamy** [paulp/sbt-extras#176]
I'm trying to run a local instance of a Akka + Kafka process with a customized `application.conf`:

```
sbt -Dconfig.file=`pwd`/application.conf run
```

But the process always uses the `src/main/resources/application.conf` file.

When I run the process directly with the JVM on the command line, it works as expected.

**Comment by paulp** [comment]
I don't know how that works but it's not related to this program. If you pass `-Dfoo=bar` to it, system property foo will be set to bar. How your particular example is interpreted by akka and/or kafka I have no idea.

**Comment by dwijnand** [comment]
@rbellamy It's probably that sbt is forking a new JVM process, rather than running your app in-process.

So you need to set the sys props with `javaOptions`.

From the command line you could call it like this:

```bash
sbt "set javaOptions in myApp += \"-Dconfig.file=`pwd`/application.conf\"" run
```

Or in the build file (e.g. `local.sbt`) with something like:

```scala
javaOptions in LocalProject("myApp") +=
  s"""-Dconfig.file=${sys.props("user.dir")}/application.conf"""
```

**Comment by rbellamy** [comment]
@dwijnand that's it exactly! Thanks...
