### ISSUE TITLE
Nonzero exit status on errors

### ISSUE THREAD

**Issue by BanzaiMan** [paulp/sbt-extras#177]
https://github.com/travis-ci/travis-ci/issues/7212 reports that `sbt`, which Travis CI uses in Scala builds, does not exit with nonzero status code when there are errors.

Could you take a look?

Thank you.

**Comment by dwijnand** [comment]
Nothing's changed in sbt-extras in over a month - we would have heard about this by now if the issue where here.

So, closing this under the assumption that the root cause is more probably https://github.com/travis-ci/travis-build/pull/939#commitcomment-20594568 which was deployed 2 hours ago.

**Comment by BanzaiMan** [comment]
Sorry for the noise, and thank you for the quick reply!
