### ISSUE TITLE
Be robust against missing .ivy2 directory

### ISSUE THREAD

**Issue by paulp** [paulp/sbt-extras#181]
On a new machine where I cloned my home directory, I had a symlink from .ivy2 to a location which didn't exist. On startup sbt fails immediately with "No such file or directory" but says absolutely nothing about ivy, or anything the least bit useful.

**Comment by dwijnand** [comment]
Is this not an sbt bug, rather than an sbt-extras bug?

**Comment by paulp** [comment]
Yes, it's an sbt bug - that's why I titled it "Be robust against..." meaning don't let the sbt bug reach us. Sorry, I'm afraid trying to fix things upstream has lost its luster for me. If you want to fix it in sbt, I applaud.

**Comment by dwijnand** [comment]
No promises, but I'll see what I can do - it's the least I can do for everything you've done.

**Comment by paulp** [comment]
Pretty sure you've done at least as much as any other single individual, so don't set the bar TOO high. 😃

**Comment by dwijnand** [comment]
In this project, sure. But you've done so much for Scala that I'm happy to (try to) take care of these niggles for you. Here's a little quo for all those years of quid you provided: https://github.com/sbt/launcher/pull/29

**Comment by paulp** [comment]
I didn't mean in this project! I meant anywhere.

**Comment by dwijnand** [comment]
Fixed upstream.
