### ISSUE TITLE
How to check if the script can be successfully called

### ISSUE THREAD

**Issue by neurolabs** [paulp/sbt-extras#182]
I want to verify that I can successfully call this script while provisioning a docker container. sbt-extras is set as an entrypoint in the docker container. I tried

    docker run -i ${DOCKER_TAG} -help || { echo "ERROR: sbt -help does not return successfully" && exit 1; }

, but `sbt -help` exits with code 1.

Shouldn't this exit with code 0?

If not, how can I verify that the script can be called?

**Comment by paulp** [comment]
I've spent my life in a fog of confusion about whether calling `-h` on a program should return success or failure. Although both my intuition and my check of half a dozen CLI programs both support that it should be success, I feel like in the past I've found reasons it should go the other way.  Unless somebody can present the argument for failure we can change it.

In the meantime I suspect `which sbt` will succeed/fail in the same way as `sbt -help` will, unless you are plagued by programs which go by the name sbt but aren't this particular sbt.

**Comment by neurolabs** [comment]
`which sbt` would work, except that the entry point of the docker container is set to the sbt script. So all I can change is the arguments.

For now I have a workaround by checking for specific output outside of the container. but I still would highly appreciate being able to check by calling the script itself.

**Comment by paulp** [comment]
You can also just run it. `sbtx about` will work if there's a project there to be built, which presumably there is if it's an entry point.

**Comment by dwijnand** [comment]
`sbt exit` is another good no-op I use sometimes.

**Comment by dwijnand** [comment]
Actually a really fast way is `sbt 'early(exit)'`.

**Comment by neurolabs** [comment]
@paulp there's no sbt project yet, it's prepared as an sbt builder, but I want to test it without mounting a project volume.

@dwijnand that's also why your suggestions are sub-optimal. I also would like not to mount an ivy cache volume without downloading all dependencies. And all your suggestions are delegated to sbt itself, which starts with dependency fetching.

**Comment by paulp** [comment]
@neurolabs your objections are legit, I'll change it.
