### ISSUE TITLE
appveyor tests

### ISSUE THREAD

**Issue by paulp** [paulp/sbt-extras#190]
Right now the badges say passing on travis, failing on appveyor, which is what I'd expect given that apparently [0.13.14 doesn't work on windows](https://github.com/sbt/sbt/issues/3086).

But then why does [the log](https://ci.appveyor.com/api/buildjobs/d2krw8y7tvubr2x3/log) sail through all the tests and declare "Build success" ?

**Comment by dwijnand** [comment]
I'm confused the other way round: why does the badge say it doesn't work on Windows when it does? The reason sbt 0.13.14 doesn't work on Windows shouldn't affect our unix or windows tests, as we mock out everything including Java (#133).

**Comment by paulp** [comment]
We will accept this confusion also. But it does seem like if the badge says failure the log should not say success.

**Comment by dwijnand** [comment]
@paulp Could you sanity check something for me, please? The README makes reference to the AppVeyor identifier "32r7s2skrgm9ubva". Is that what you see at https://ci.appveyor.com/project/paulp/sbt-extras/settings? I can't see those settings myself.

**Comment by paulp** [comment]
It says webhook url is `https://ci.appveyor.com/api/github/webhook?id=w1tqbwr7d4doak7v` and that's the closest thing to an identifier I see.
