### ISSUE TITLE
Add CI validation for the README snippets

### ISSUE THREAD

**Issue by dwijnand** [paulp/sbt-extras#191]
It would be really good if we had a system that ensured our README snippets never bit rot.

However such a system shouldn't be fragile and require constant adult supervision and maintenance..

**Comment by mcanlas** [comment]
Are there projects that already have a mechanism for this?

**Comment by dwijnand** [comment]
Not really. https://github.com/tpolecat/tut is the closest thing.

We can go the high-tech route of parsing the markdown and extracting code blocks of a given shape, say those that start with "```bash", and then validate those.

Or we can go the low-tech route and use markers (invisible in the rendered form) to chop out the code block and validate it.

Here I'd go with the latter, YAGNI route.

**Comment by dwijnand** [comment]
Perhaps CI could push "Update README shell session snippets" commits rather than fail the build..

**Comment by dwijnand** [comment]
I think there's some prior art one could look in @alexarchambault's handy work in https://github.com/coursier/coursier.

**Comment by alexarchambault** [comment]
@dwijnand I [removed](https://github.com/coursier/coursier/pull/941) the need to update the README some time ago… It was handled all by sbt-release, and all was running on my machine (not the CI).

**Comment by dwijnand** [comment]
This would require having a `java` executable in CI, either a real one or a mocked up one, and I think I'd rather leave this using the minimal TravisCI image & not doing the mocking.

So I guess we can keep using adult supervision.
