### ISSUE TITLE
"Ignoring option MaxPermSize" warning when JDK9 or higher due to JEP-223

### ISSUE THREAD

**Issue by xuwei-k** [paulp/sbt-extras#207]
- https://github.com/paulp/sbt-extras/blob/d28a7e41fdb49941e8ba7d50cdb9f9cb98efd26a/sbt#L175
- https://github.com/paulp/sbt-extras/blob/d28a7e41fdb49941e8ba7d50cdb9f9cb98efd26a/sbt#L195-L209
- https://github.com/scala/scala/commit/72076e59257da72f962d4101d87ff5507da2
- http://openjdk.java.net/jeps/223

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt-launcher-package/pull/209
- https://github.com/sbt/sbt-launcher-package/commit/f77c15496b18324e893f7ba3c43f5c78433d3833#diff-edd0ab5838b2fa424d30f94df800e1f9R155

**Comment by dwijnand** [comment]
Fixed, I think with #213.
