### ISSUE TITLE
sbt 1.x support

### ISSUE THREAD

**Issue by alltonp** [paulp/sbt-extras#216]
Hi,

I like sbt-extras. Are there any plans to support SBT 1.X?

Many thanks,
Paul

**Comment by dwijnand** [comment]
See https://github.com/paulp/sbt-extras/pull/205.

TL;DR Not yet.

**Comment by jodersky** [comment]
I came here from jodersky/sbt-gpg#9, and was told that sbt-extras now supports sbt 1. @dwijnand, can this issue be closed?

**Comment by djspiewak** [comment]
I think this issue ended up getting conflated with #205, which is about the *default* versions (i.e. what you get if you run `sbt new`). I'm guessing the OP of this issue (and certainly @miguno referring to here) intended for this issue to refer to the support for launching SBT on projects using >=1.x, which sbt-extras already supports. So I would also be in favor of closing this, as it seems to lead to some confusion.

**Comment by dwijnand** [comment]
SGTM.  I tried being more specific in #226.
