### ISSUE TITLE
RFE: Verify sbt-launch.jar signatures

### ISSUE THREAD

**Issue by djspiewak** [paulp/sbt-extras#220]
Key fingerprint should be hard-coded into the script, and ideally the commit which does the hard-coding should be signed (`git commit -S`). Effectively, the script itself becomes a cryptographic assertion of the validity of the downloaded `sbt-launch.jar` file. This then allows the SBT trust ecosystem to be rooted on trust in wherever the sbt-extras script came from, which is usually one of CI server preinstallation, `brew`, `git clone`, or simply having the script copied into your repo.

Making things slightly more complex is the fact that older launchers were published without cryptographic signing (e.g. 0.9). Also signature verification would require `gpg`. I would suggest that, if `gpg` is absent, we just don't verify the signing (rather than failing startup).

**Comment by dwijnand** [comment]
In #247 we verify that the MD5's match, which, while not impenetrable, I'm thinking is probably good enough...
