### ISSUE TITLE
Update fallback sbt version to 1.x

### ISSUE THREAD

**Issue by dwijnand** [paulp/sbt-extras#226]
It is a best practice in sbt builds to define `sbt.version` in `project/build.properties`.  sbt-extras uses that version (for some more specifics see https://github.com/paulp/sbt-extras/pull/205#issuecomment-381094395), but also has a fallback sbt version for some fringe cases (the ones that I can remember now):

* when `sbt.version` _isn't_ define (which, again, is a bad practice)
* when using `sbt new`, which is to bootstrap a new build

Note for `sbt new` you can still use a different version like so: `sbt new -sbt-version 1.2.7`.

See #205 which wasn't landed as sbt 1.x was deemed unready.

**Comment by dwijnand** [comment]
I believe sbt 1.x to be stable enough to land something like #205 now, I just haven't had the time.  I'm not sure, but I think Paul would be fine with that now too.

**Comment by paulp** [comment]
I'm not programming in scala anymore. I defer to @dwijnand on this matter, and everything else related to this repo from now on.

**Comment by dwijnand** [comment]
Thanks, Paul.  I believe it was fair to be cautious, but it's hard to hold back the tide forever.  If any issues crop up we'll forward-fix them.
