### ISSUE TITLE
0.7.7 is broken

### ISSUE THREAD

**Issue by NeQuissimus** [paulp/sbt-extras#246]
http://simple-build-tool.googlecode.com/files/sbt-launch-0.7.7.jar is 404 and `sbt-extras` will hence no longer be able to download it.

**Comment by dwijnand** [comment]
STOP! EVERYTHING!

😆

Duplicate of #210, but I guess we can fix this by changing the URL to https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/simple-build-tool/sbt-launch-0.7.7.jar.

I'm not dying to have sbt 0.7 support in sbt-extras, so PR welcome.

**Comment by NeQuissimus** [comment]
I'd vote for just removing it...

**Comment by dwijnand** [comment]
I'm fine with that too.

**Comment by dwijnand** [comment]
Fixed in #259
