### ISSUE TITLE
Consider running & enforcing shfmt

### ISSUE THREAD

**Issue by dwijnand** [paulp/sbt-extras#249]
shfmt (https://github.com/mvdan/sh) is a formatter for shell scripts.

Perhaps sbt-extras should run it and enforce it in CI.

**Comment by NeQuissimus** [comment]
`shfmt -d -i 2 -ci ./sbt` is likely what we would want.

(`-d` = error out if misformatted, also outputs a diff; `-i 2` = indent using 2 spaces; `-ci` = indent switch cases)
