### ISSUE TITLE
java9rtexport?

### ISSUE THREAD

**Issue by er1c** [paulp/sbt-extras#282]
```
[info] Compiling 53 Scala sources and 1 Java source to /home/runner/work/fm-common/fm-common/core/jvm/target/scala-2.11/test-classes ...
[error] /home/runner/work/fm-common/fm-common/core/jvm/src/test/scala/fm/common/TestPunycode.scala:346:20: object idn is not a member of package sun.net
[error]     import sun.net.idn.{Punycode => SunPunycode}
[error]    
```

I think it's related to the 'other' sbt launcher including the java9rtexport in the classpath

https://github.com/sbt/sbt-launcher-package/tree/master/java9-rt-export/src/main/java/io/github/retronym/java9rtexport / https://github.com/retronym/java9-rt-export

Is there a sbt-extras best practice for handling this?

**Comment by dwijnand** [comment]
Assuming that `TestPunycode` is testing the JDK's usage of Punycode in its `java.net.IDN` behaviour, I'd switch the test from using `Punycode.encode` and `Punycode.decode` to `IDN.toASCII` and `IDN.toUnicode`, respectively.

**Comment by er1c** [comment]
@dwijnand thanks for the tip, local tests pass after changing to `IDN`, I'll push to github actions and verify if it is fixed and close ticket as appropriate

**Comment by er1c** [comment]
Well, the Punycode tests I have test something completely different than `IDN` (which is also in my unit tests)

I was able to hack around the issue via: https://github.com/er1c/fm-common/commit/179ce9dcf3579dec4c6d4ad22d5620d36efa62d0 and creating the `rt.jar` and adding the `-Dscala.ext.dirs=../java9-rt-ext` (which is a directory that simply includes the `rt.jar`)

@dwijnand  I have no idea if this is too "edge case" specific.  I can create a PR that uses the same `java9-rt-ext` as the official sbt binary, but I don't know if  you  want to include that level of complication in `sbt-extras`.  If the answer is "yes" I can create the PR, if "maybe"  I can also create the PR.  But if your intuition is "no" then I won't bother :) and simply use the official sbt launcher.

**Comment by dwijnand** [comment]
Yeah, I think I'd rather keep things simple.

If I understand the situation correctly, that Punycode is the JDK is just an implementation detail for IDN, and wasn't meant to be available for external usage.  So if they chose to hide it, I think we should move to something else, not try to bring it back.

**Comment by er1c** [comment]
@dwijnand thank you for your engagement on this issue, it really does help a lot to get to an early resolution regardless on outcomes!
