### ISSUE TITLE
Support Windows pleasantly

### ISSUE THREAD

**Issue by copumpkin** [paulp/sbt-extras#82]
I realize this probably isn't at the top of @paulp's concerns, but I figured I'd record the issue in case someone wanted to tackle it (that someone might eventually be me).

The script currently references `stty`, which isn't very Windows-friendly. I don't expect the whole thing to work out of the box on Windows, given it's a bash script, but it'd be helpful not to do things that are actually quite hard to get working nicely on Windows/msys/cygwin.

**Comment by paulp** [comment]
I think the "official" sbt runner is the place for this.
