### ISSUE TITLE
JAVA_HOME, -java-home and java binary incompatibilities

### ISSUE THREAD

**Issue by fommil** [paulp/sbt-extras#83]
I typically use Java7 but I have an awkward project that must be compiled/run under a specific version of java 6.

When launching, I have tried both setting `JAVA_HOME` and passing `-java-home`. This version of java is correctly picked up by sbt and that is indeed the version that a `System.getProperty("java.version")` will output.

However, the java files in my project are being compiled by java 7!!

I suspect there is some part of `sbt` that is calling out to the `javac` binary without respecting the java-home, because when I set

```
export JAVA_HOME=...
export PATH=$JAVA_HOME/bin:$PATH
sbt
```

then everything works as expected.

Any ideas?

**Comment by fommil** [comment]
any progress on this? I'm still using my `.javahome` hack in my custom `sbt` launcher.

**Comment by dwijnand** [comment]
@fommil Do you mind seeing if my branch attached to #95 works for you?
