### ISSUE TITLE
sbt 0.13.0 won't work with JAVA_HOME logic

### ISSUE THREAD

**Issue by dwijnand** [paulp/sbt-extras#99]
The logic that picks up `JAVA_HOME` and silently sets `javaHome` won't work for 0.13.0 as `warn` wasn't available(?)

     $ sbt
    [info] Loading global plugins from /Users/dnw/.sbt/0.13/plugins
    [info] Loading project definition from /Users/dnw/Desktop/t
    [info] Set current project to t (in build file:/Users/dnw/Desktop/t/)
    [error] Not a valid command: warn (similar: start)
    [error] Not a valid project ID: warn
    [error] Expected ':' (if selecting a configuration)
    [error] Not a valid key: warn (similar: run, clean, watch)
    [error] warn
    [error]     ^

More info available in `~/.sbt/boot/update.log`

**Comment by paulp** [comment]
Is there some reason to use sbt 0.13.0? I'm definitely not interested in supporting it. (I'm still getting by without sbt-extras at all.)

**Comment by dwijnand** [comment]
Looked to me like sbt-extras was trying to handle [a bunch of different versions][different versions] and this looked like a regression.

  [different versions]: https://github.com/paulp/sbt-extras/blob/e30153f02c4caa47de5dd7ce124a969478d3f5a4/test/test_helper.bash#L23-L27

In my case I worked around it by seemlessly upgrading to 0.13.7, but I thought I should raise this.

What are you using instead? AFAIK there are two maybe more alternatives available:

  * [sbt-launcher-package](https://github.com/sbt/sbt-launcher-package/blob/1735b0b7ecd4636ce2890961024e015e74c1c2db/src/universal/bin/sbt-launch-lib.bash)
  * [sbt-native-packager](https://github.com/sbt/sbt-native-packager/blob/5b41248d6392261c1c6be2e01cb11963177b8562/src/main/resources/com/typesafe/sbt/packager/archetypes/bash-template)

**Comment by paulp** [comment]
I'm using "brew install sbt" which leads back to https://dl.bintray.com/sbt/native-packages/sbt/0.13.7/sbt-0.13.7.tgz .

**Comment by eric** [comment]
From the README:

> It works with sbt 0.13.0 projects and (in principle) all earlier versions.

It _would_ work with 0.13.0 and earlier if it weren't for the two lines that call `warn` and `info`.
